---
# Common files between the dists
- name: krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - aad_krb5_conf
    - aad_sssd

- name: sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart sssd
  tags:
    - aad_sssd_conf
    - aad_sssd

- name: check sssd.conf configuration
  shell:
    cmd: "sssctl config-check"
  register: result
  failed_when: false

- debug:
    var: result.stdout
