---
#
# Configure Samba firewalld
#

- name: install firewalld package
  package:
    name: firewalld
    state: present

- name: ensure firewalld is running and enabled on boot
  service:
    name: firewalld
    state: started
    enabled: true

- name: check firewalld status
  shell: 'echo $(systemctl is-active firewalld)'
  register: service_firewalld

- debug:
    msg: '{{service_firewalld}}'

- name: 'configure firewalld for samba ports'
  firewalld:
    service: samba
    permanent: true
    immediate: true
    state: enabled
  when: service_firewalld.stdout == "active"
